# Generated by Django 3.0.7 on 2020-06-05 01:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nationallity',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
