# Generated by Django 3.0.7 on 2020-06-05 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('publish_date', models.DateField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('P', 'Published'), ('W', 'Withdrawn'), ('D', 'Draft')], default='P', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='Author.Author')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_books', to='Book.Topic')),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
